[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.1.2"
  export = ["dec5_gql"]
  icon = "docs/icon.png"
  keywords = ["Type/GraphQL","Category/Service","Internal/http"]
  name = "GQL-Jan12"
  org = "isurupiyarathnarucji"
  version = "1.0.1"
